"""Reset Database and add some test data."""

from ..entities.entity_base import  EntityBase
from ..entities.Authentication.user_entity import UserEntity
from ..database import engine

from sqlalchemy.orm import Session
from ..models.Authentication.user import User
import sqlalchemy
from ..env import getenv
from ..services.Authentication.authentication_service import AuthenticationService

EntityBase.metadata.drop_all(engine)
EntityBase.metadata.create_all(engine)

def _engine_str(database=getenv("POSTGRES_DATABASE")) -> str:
    """Helper function for reading settings from environment variables to produce connection string."""
    dialect = "postgresql+psycopg2"
    user = getenv("POSTGRES_USER")
    password = getenv("POSTGRES_PASSWORD")
    host = getenv("POSTGRES_HOST")
    port = getenv("POSTGRES_PORT")
    return f"{dialect}://{user}:{password}@{host}:{port}/{database}"

engine = sqlalchemy.create_engine(_engine_str(), echo=True)
"""Application-level SQLAlchemy database engine."""

session: Session = Session(engine)

service = AuthenticationService(session=session)

mod: User = User(
    id=0,
    email="johndoe@example.com",
    username="johndoe",
    hashed_password=f"{service._get_password_hash(password='secret')}",
    full_name="John Doe",
    disabled=False
)

mod2: User = User(
    id=1,
    email="johngreen@example.com",
    username="johngreen",
    hashed_password="fakehashsecret2",
    full_name="John Green",
    disabled=True
)

ent = UserEntity.from_model(mod)
ent2 = UserEntity.from_model(mod2)

session.add(ent)
session.add(ent2)

from sqlalchemy import text
from sqlalchemy.orm import Session, DeclarativeBase, InstrumentedAttribute


def reset_table_id_seq(
    session: Session,
    entity: type[DeclarativeBase],
    entity_id_column: InstrumentedAttribute[int],
    next_id: int,
) -> None:
    """Reset the ID sequence of an entity table.

    Args:
        session (Session) - A SQLAlchemy Session
        entity (DeclarativeBase) - The SQLAlchemy Entity table to target
        entity_id_column (MappedColumn) - The ID column (should be an int column)
        next_id (int) - Where the next inserted, autogenerated ID should begin

    Returns:
        None"""
    table = entity.__table__
    id_column_name = entity_id_column.name
    sql = text(f"ALTER SEQUENCe {table}_{id_column_name}_seq RESTART WITH {next_id}")
    session.execute(sql)

reset_table_id_seq(session=session, entity=UserEntity, entity_id_column=UserEntity.id, next_id=2)

session.commit()
session.close()
